CREATE TABLE complaint
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username            VARCHAR(255),
    content          VARCHAR(255)                             NOT NULL,
    deleted          BOOLEAN                                  NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_complaint PRIMARY KEY (id)
);